# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Jet.destroy_all

user1 = User.create(password: "malteser", email: "Diana@gmail.com")
user2 = User.create(password: "chickens", email: "John@gmail.com")
user3 = User.create(password: "samantha", email: "Doyvdas@gmail.com")
user4 = User.create(password: "crispy", email: "paul@gmail.com")
user5 = User.create(password: "banana", email: "kenniy@gmail.com")
user6 = User.create(password: "smurfaliend", email: "tom@gmail.com")
user7 = User.create(password: "cabanssa", email: "Ben@gmail.com")
user8 = User.create(password: "Plutadfbo", email: "Sarah@gmail.com")
user9 = User.create(password: "Neptune", email: "Penny@gmail.com")
user10 = User.create(password: "simbasdfsdf", email: "Sandra@gmail.com")
user11 = User.create(password: "Tottenham", email: "Dagmara@gmail.com")
user12 = User.create(password: "Parissdfsdf", email: "Cynthia@gmail.com")
user13 = User.create(password: "blackie", email: "Filippa@gmail.com")
user14 = User.create(password: "principle", email: "Regina@gmail.com")
user15 = User.create(password: "Trafalgar", email: "Lyndon@gmail.com")
user16 = User.create(password: "Spainwfsd", email: "Boris@gmail.com")
user17 = User.create(password: "Portugal", email: "Kenneth@gmail.com")
user18 = User.create(password: "covid19sdf", email: "Oliver@gmail.com")


jet1 = Jet.create(model: "Grumman Gulfstream II", max_speed: 501, max_range: 2000, fuel_consumption: 50, description: "set up with horizontal sleeping positions and shower", price_hourly: 5000, user: user1)
jet2 = Jet.create(model: "Learjet 23", max_speed: 600, max_range: 2510, fuel_consumption: 40, description: "set up with bar and conference table", price_hourly: 2000, user: user2)
jet3 = Jet.create(model: "Global 7500", max_speed: 500, max_range: 2400, fuel_consumption: 70, description: "set up with snooker table", price_hourly: 7000, user: user3)
jet4 = Jet.create(model: "Cessna Citation Longitude", max_speed: 550, max_range: 4000, fuel_consumption: 90, description: "comes with Michel star chef", price_hourly: 8000, user: user3)
jet5 = Jet.create(model: "Pilatus PC-24", max_speed: 590, max_range: 4200, fuel_consumption: 35, description: "set up for yoga studio", price_hourly: 2900, user: user3)
jet6 = Jet.create(model: "Gulfstream G600", max_speed: 700, max_range: 3000, fuel_consumption: 70, description: "includes gym and sauna", price_hourly: 4200, user: user17)
jet7 = Jet.create(model: "Dassault Falcon 6X", max_speed: 740, max_range: 3400, fuel_consumption: 55, description: "includes music recording studio", price_hourly: 6200, user: user18)
jet8 = Jet.create(model: "Phenom 100V+", max_speed: 680, max_range: 3600, fuel_consumption: 40, description: "includes DJ, bar and bouncer", price_hourly: 5200, user: user17)
jet9 = Jet.create(model: "Embraer Legacy 700", max_speed: 640, max_range: 5400, fuel_consumption: 39, description: "includes playstation 4 and xbox", price_hourly: 6200, user: user15)
jet10 = Jet.create(model: "Dassault Falcon 50", max_speed: 620, max_range: 4400, fuel_consumption: 52, description: "includes access to private villa in Portugal", price_hourly: 7200, user: user3)
jet11 = Jet.create(model: "Cirrus Vision SF50", max_speed: 510, max_range: 4100, fuel_consumption: 58, description: "provided with unlimited beer and wine", price_hourly: 9200, user: user12)
jet12 = Jet.create(model: "Cessna Citation X", max_speed: 490, max_range: 4900, fuel_consumption: 59, description: "features exhibition gallery of fine art", price_hourly: 6200, user: user11)
jet13 = Jet.create(model: "Embraer Legacy 600", max_speed: 515, max_range: 4010, fuel_consumption: 65, description: "set up for dinner party", price_hourly: 4200, user: user10)
jet14 = Jet.create(model: "Cessna Citation Columbus", max_speed: 700, max_range: 2400, fuel_consumption: 70, description: "dog-friendly", price_hourly: 3200, user: user1)
jet15 = Jet.create(model: "Aerion AS2", max_speed: 710, max_range: 5000, fuel_consumption: 65, description: "cat-friendly", price_hourly: 6200, user: user1)
jet16 = Jet.create(model: "Dassault Falcon 900LX", max_speed: 754, max_range: 4800, fuel_consumption: 80, description: "capable of taking 500kg of luggage", price_hourly: 5200, user: user4)
jet17 = Jet.create(model: "SyberJet SJ30i", max_speed: 654, max_range: 2900, fuel_consumption: 75, description: "able to take-off/land on runways only 400m", price_hourly: 6200, user: user6)
jet18 = Jet.create(model: "Cessna Citation CJ3+/4", max_speed: 667, max_range: 3400, fuel_consumption: 85, description: "only available for 14 day bookings", price_hourly: 4200, user: user6)
jet19 = Jet.create(model: "Embraer Legacy 450", max_speed: 690, max_range: 4400, fuel_consumption: 51, description: "set-up for ball-room dancing", price_hourly: 7200, user: user7)
jet20 = Jet.create(model: "Embraer Legacy 500", max_speed: 785, max_range: 6400, fuel_consumption: 48, description: "includes mini-golf", price_hourly: 8200, user: user3)
jet21 = Jet.create(model: "HondaJet Elite", max_speed: 900, max_range: 4400, fuel_consumption: 70, description: "set up as a casino", price_hourly: 8300, user: user1)
jet22 = Jet.create(model: "Grumman Gulfstream II", max_speed: 501, max_range: 2000, fuel_consumption: 50, description: "set up with horizontal sleeping positions and shower", price_hourly: 5000, user: user1)
jet23 = Jet.create(model: "Learjet 23", max_speed: 600, max_range: 2510, fuel_consumption: 40, description: "set up with bar and conference table", price_hourly: 2000, user: user2)
jet24 = Jet.create(model: "Global 7500", max_speed: 500, max_range: 2400, fuel_consumption: 70, description: "set up with snooker table", price_hourly: 7000, user: user3)
jet25 = Jet.create(model: "Cessna Citation Longitude", max_speed: 550, max_range: 4000, fuel_consumption: 90, description: "comes with Michel star chef", price_hourly: 8000, user: user3)
jet26 = Jet.create(model: "Pilatus PC-24", max_speed: 590, max_range: 4200, fuel_consumption: 35, description: "set up for yoga studio", price_hourly: 2900, user: user2)
jet27 = Jet.create(model: "Gulfstream G600", max_speed: 700, max_range: 3000, fuel_consumption: 70, description: "includes gym and sauna", price_hourly: 4200, user: user2)
jet28 = Jet.create(model: "Dassault Falcon 6X", max_speed: 740, max_range: 3400, fuel_consumption: 55, description: "includes music recording studio", price_hourly: 6200, user: user9)
jet29 = Jet.create(model: "Phenom 100V+", max_speed: 680, max_range: 3600, fuel_consumption: 40, description: "includes DJ, bar and bouncer", price_hourly: 5200, user: user10)
jet30 = Jet.create(model: "Embraer Legacy 700", max_speed: 640, max_range: 5400, fuel_consumption: 39, description: "includes playstation 4 and xbox", price_hourly: 6200, user: user10)
jet31 = Jet.create(model: "Dassault Falcon 50", max_speed: 620, max_range: 4400, fuel_consumption: 52, description: "includes access to private villa in Portugal", price_hourly: 7200, user: user10)
jet32 = Jet.create(model: "Cirrus Vision SF50", max_speed: 510, max_range: 4100, fuel_consumption: 58, description: "provided with unlimited beer and wine", price_hourly: 9200, user: user13)
jet33 = Jet.create(model: "Cessna Citation X", max_speed: 490, max_range: 4900, fuel_consumption: 59, description: "features exhibition gallery of fine art", price_hourly: 6200, user: user12)
jet34 = Jet.create(model: "Embraer Legacy 600", max_speed: 515, max_range: 4010, fuel_consumption: 65, description: "set up for dinner party", price_hourly: 4200, user: user12)
jet35 = Jet.create(model: "Cessna Citation Columbus", max_speed: 700, max_range: 2400, fuel_consumption: 70, description: "dog-friendly", price_hourly: 3200, user: user13)
jet36 = Jet.create(model: "Aerion AS2", max_speed: 710, max_range: 5000, fuel_consumption: 65, description: "cat-friendly", price_hourly: 6200, user: user14)
jet37 = Jet.create(model: "Dassault Falcon 900LX", max_speed: 754, max_range: 4800, fuel_consumption: 80, description: "capable of taking 500kg of luggage", price_hourly: 5200, user: user9)
jet38 = Jet.create(model: "SyberJet SJ30i", max_speed: 654, max_range: 2900, fuel_consumption: 75, description: "able to take-off/land on runways only 400m", price_hourly: 6200, user: user9)
jet39 = Jet.create(model: "Cessna Citation CJ3+/4", max_speed: 667, max_range: 3400, fuel_consumption: 85, description: "only available for 14 day bookings", price_hourly: 4200, user: user9)
jet40 = Jet.create(model: "Embraer Legacy 450", max_speed: 690, max_range: 4400, fuel_consumption: 51, description: "set-up for ball-room dancing", price_hourly: 7200, user: user8)
jet41 = Jet.create(model: "Embraer Legacy 500", max_speed: 785, max_range: 6400, fuel_consumption: 48, description: "includes mini-golf", price_hourly: 8200, user: user8)
jet42 = Jet.create(model: "Grumman Gulfstream II", max_speed: 501, max_range: 2000, fuel_consumption: 50, description: "set up with horizontal sleeping positions and shower", price_hourly: 5000, user: user1)
jet43 = Jet.create(model: "Learjet 23", max_speed: 600, max_range: 2510, fuel_consumption: 40, description: "set up with bar and conference table", price_hourly: 2000, user: user15)
jet44 = Jet.create(model: "Global 7500", max_speed: 500, max_range: 2400, fuel_consumption: 70, description: "set up with snooker table", price_hourly: 7000, user: user17)
jet45 = Jet.create(model: "Cessna Citation Longitude", max_speed: 550, max_range: 4000, fuel_consumption: 90, description: "comes with Michel star chef", price_hourly: 8000, user: user18)
jet46 = Jet.create(model: "Pilatus PC-24", max_speed: 590, max_range: 4200, fuel_consumption: 35, description: "set up for yoga studio", price_hourly: 2900, user: user16)
jet47 = Jet.create(model: "Gulfstream G600", max_speed: 700, max_range: 3000, fuel_consumption: 70, description: "includes gym and sauna", price_hourly: 4200, user: user14)
jet48 = Jet.create(model: "Dassault Falcon 6X", max_speed: 740, max_range: 3400, fuel_consumption: 55, description: "includes music recording studio", price_hourly: 6200, user: user10)
jet49 = Jet.create(model: "Phenom 100V+", max_speed: 680, max_range: 3600, fuel_consumption: 40, description: "includes DJ, bar and bouncer", price_hourly: 5200, user: user1)
jet50 = Jet.create(model: "Embraer Legacy 700", max_speed: 640, max_range: 5400, fuel_consumption: 39, description: "includes playstation 4 and xbox", price_hourly: 6200, user: user2)
jet51 = Jet.create(model: "Dassault Falcon 50", max_speed: 620, max_range: 4400, fuel_consumption: 52, description: "includes access to private villa in Portugal", price_hourly: 7200, user: user7)
jet52 = Jet.create(model: "Cirrus Vision SF50", max_speed: 510, max_range: 4100, fuel_consumption: 58, description: "provided with unlimited beer and wine", price_hourly: 9200, user: user7)
jet53 = Jet.create(model: "Cessna Citation X", max_speed: 490, max_range: 4900, fuel_consumption: 59, description: "features exhibition gallery of fine art", price_hourly: 6200, user: user6)
jet54 = Jet.create(model: "Embraer Legacy 600", max_speed: 515, max_range: 4010, fuel_consumption: 65, description: "set up for dinner party", price_hourly: 4200, user: user5)
jet55 = Jet.create(model: "Cessna Citation Columbus", max_speed: 700, max_range: 2400, fuel_consumption: 70, description: "dog-friendly", price_hourly: 3200, user: user5)
jet56 = Jet.create(model: "Aerion AS2", max_speed: 710, max_range: 5000, fuel_consumption: 65, description: "cat-friendly", price_hourly: 6200, user: user5)
jet57 = Jet.create(model: "Dassault Falcon 900LX", max_speed: 754, max_range: 4800, fuel_consumption: 80, description: "capable of taking 500kg of luggage", price_hourly: 5200, user: user1)
jet58 = Jet.create(model: "SyberJet SJ30i", max_speed: 654, max_range: 2900, fuel_consumption: 75, description: "able to take-off/land on runways only 400m", price_hourly: 6200, user: user3)
jet59 = Jet.create(model: "Cessna Citation CJ3+/4", max_speed: 667, max_range: 3400, fuel_consumption: 85, description: "only available for 14 day bookings", price_hourly: 4200, user: user18)
jet60 = Jet.create(model: "Embraer Legacy 450", max_speed: 690, max_range: 4400, fuel_consumption: 51, description: "set-up for ball-room dancing", price_hourly: 7200, user: user12)
jet61 = Jet.create(model: "Embraer Legacy 500", max_speed: 785, max_range: 6400, fuel_consumption: 48, description: "includes mini-golf", price_hourly: 8200, user: user9)
jet62 = Jet.create(model: "HondaJet Elite", max_speed: 900, max_range: 4400, fuel_consumption: 70, description: "set up as a casino", price_hourly: 8300, user: user8)

